#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub enum UdpPorts {
    Echo,
    Discard,
    Systat,
    Daytime,
    Qotd,
    MessageSend,
    Chargen,
    Time,
    HostNameServer,
    Tacacs,
    Dns,
    BootpServer,
    BootpClient,
    Tftp,
    Netrjs,
    Http,
    Kerberos,
    DiCom,
    CcsoNameServer,
    RTelnet,
    IBMSnaGateway,
    OncRpc,
    McIDAS,
    UucpPathService,
    SqlServices,
    Ntp,
    NxEdit,
    DceEndpointResolution,
    MicrosoftEpmap,
    NetbiosNameService,
    NetbiosDatagramService,
    Bftp,
    Sgmp,
    Dmsp,
    Snmp,
    Snmptrap,
    NetworkPostScript,
    Vmnet,
    Xdmcp,
    Irc,
    Smux,
    AppletalkRouting,
    AnsiZ3950,
    Ipx,
    Mpp,
    Imap3,
    Esro,
    Arcisdms,
    Bgmp,
    HttpMgmt,
    PkixTsp,
    PtpEvent,
    PtpGeneral,
    MatipA,
    MatipB,
    CloantoNet1,
    Odmr,
    Rpc2portmap,
    Codaauth2,
    Securecast1,
    ClearCaseAlbd,
    AmigaEnvoy,
    HpDataAlarmManager,
    Aurp,
    DecnetPlus,
    Ups,
    Slp,
    Nntp,
    MobileIpAgent,
    Https,
    Snpp,
    Quick_MicrosoftDs,
    Kpasswd,
    Tcpnethaspsrv,
    Retrospect,
    IsakmpIke,
    Modbus,
    CitadelFcp,
    Comsat,
    Who,
    Syslog,
    Rip,
    Ripng,
    Ncp,
    Timed,
    Rpc,
    Netwall,
    Commerce,
    Dhcpv6Client,
    Dhcpv6Server,
    NewRwho,
    Rtsp,
    Rmonitor,
    Monitor,
    Nntps,
    HttpRpcEpMap,
    AsfRmcpIpmi,
    Ipp,
    Msdp,
    SupportsoftNexusControl,
    Sanity,
    Ldp,
    IeeeMms,
    TincVpn,
    IbmRmc,
    Doom,
    CorbaIiopSsl,
    RealmRusd,
    Vatp,
    LinuxHaHeartbeat,
    Olsr,
    KerberosAdmin,
    KerberosIv,
    Rrh,
    TellSend,
    MdbsDaemon,
    ModbusTcpSecurity,
    NetconfSsh,
    NetconfBeep,
    NetconfSoapHttps,
    NetconfSoapBeep,
    Gdoi,
    DnsOverQuic,
    DnsOverDtls,
    OwampControl,
    TwampControl,
    FtpsData,
    FtpsControl,
    Nas,
    TelnetTls,
    Pop3s,
    WakeOnLan,
    TorparkControl,

    Pointcast,
    CentroErp,
    CupsAdmin,
    KerberosMaster,
    PasswdServer,
    UserregServer,
    Krbupdate,
    Msx,
    BrocadeSmiSRpc,
    BrocadeSmiSRpcSsl,
    VmwareEsxi,
    PsWakeOnLan,
    ZosNfs
}

impl UdpPorts {

    pub fn from_code(code: u16) -> Result<Self, String> {
        for c in [
            Self::Echo,
            Self::Discard,
            Self::Systat,
            Self::Daytime,
            Self::Qotd,
            Self::MessageSend,
            Self::Chargen,
            Self::Time,
            Self::HostNameServer,
            Self::Tacacs,
            Self::Dns,
            Self::BootpServer,
            Self::BootpClient,
            Self::Tftp,
            Self::Netrjs,
            Self::Http,
            Self::Kerberos,
            Self::DiCom,
            Self::CcsoNameServer,
            Self::RTelnet,
            Self::IBMSnaGateway,
            Self::OncRpc,
            Self::McIDAS,
            Self::UucpPathService,
            Self::SqlServices,
            Self::Ntp,
            Self::NxEdit,
            Self::DceEndpointResolution,
            Self::MicrosoftEpmap,
            Self::NetbiosNameService,
            Self::NetbiosDatagramService,
            Self::Bftp,
            Self::Sgmp,
            Self::Dmsp,
            Self::Snmp,
            Self::Snmptrap,
            Self::NetworkPostScript,
            Self::Vmnet,
            Self::Xdmcp,
            Self::Irc,
            Self::Smux,
            Self::AppletalkRouting,
            Self::AnsiZ3950,
            Self::Ipx,
            Self::Mpp,
            Self::Imap3,
            Self::Esro,
            Self::Arcisdms,
            Self::Bgmp,
            Self::HttpMgmt,
            Self::PkixTsp,
            Self::PtpEvent,
            Self::PtpGeneral,
            Self::MatipA,
            Self::MatipB,
            Self::CloantoNet1,
            Self::Odmr,
            Self::Rpc2portmap,
            Self::Codaauth2,
            Self::Securecast1,
            Self::ClearCaseAlbd,
            Self::AmigaEnvoy,
            Self::HpDataAlarmManager,
            Self::Aurp,
            Self::DecnetPlus,
            Self::Ups,
            Self::Slp,
            Self::Nntp,
            Self::MobileIpAgent,
            Self::Https,
            Self::Snpp,
            Self::Quick_MicrosoftDs,
            Self::Kpasswd,
            Self::Tcpnethaspsrv,
            Self::Retrospect,
            Self::IsakmpIke,
            Self::Modbus,
            Self::CitadelFcp,
            Self::Comsat,
            Self::Who,
            Self::Syslog,
            Self::Rip,
            Self::Ripng,
            Self::Ncp,
            Self::Timed,
            Self::Rpc,
            Self::Netwall,
            Self::Commerce,
            Self::Dhcpv6Client,
            Self::Dhcpv6Server,
            Self::NewRwho,
            Self::Rtsp,
            Self::Rmonitor,
            Self::Monitor,
            Self::Nntps,
            Self::HttpRpcEpMap,
            Self::AsfRmcpIpmi,
            Self::Ipp,
            Self::Msdp,
            Self::SupportsoftNexusControl,
            Self::Sanity,
            Self::Ldp,
            Self::IeeeMms,
            Self::TincVpn,
            Self::IbmRmc,
            Self::Doom,
            Self::CorbaIiopSsl,
            Self::RealmRusd,
            Self::Vatp,
            Self::LinuxHaHeartbeat,
            Self::Olsr,
            Self::KerberosAdmin,
            Self::KerberosIv,
            Self::Rrh,
            Self::TellSend,
            Self::MdbsDaemon,
            Self::ModbusTcpSecurity,
            Self::NetconfSsh,
            Self::NetconfBeep,
            Self::NetconfSoapHttps,
            Self::NetconfSoapBeep,
            Self::Gdoi,
            Self::DnsOverQuic,
            Self::DnsOverDtls,
            Self::OwampControl,
            Self::TwampControl,
            Self::FtpsData,
            Self::FtpsControl,
            Self::Nas,
            Self::TelnetTls,
            Self::Pop3s,
            Self::WakeOnLan,
            Self::TorparkControl,

            Self::Pointcast,
            Self::CentroErp,
            Self::CupsAdmin,
            Self::KerberosMaster,
            Self::PasswdServer,
            Self::UserregServer,
            Self::Krbupdate,
            Self::Msx,
            Self::BrocadeSmiSRpc,
            Self::BrocadeSmiSRpcSsl,
            Self::VmwareEsxi,
            Self::PsWakeOnLan,
            Self::ZosNfs
        ] {
            let (x, w) = c.get_code();
            if x >= code && x + w <= code {
                return Ok(c);
            }
        }

        Err(format!("Couldn't find for code: {}", code))
    }

    pub fn get_code(&self) -> (u16, u16) {
        match self {
            Self::Echo => (7, 0),
            Self::Discard => (9, 0),
            Self::Systat => (11, 0),
            Self::Daytime => (13, 0),
            Self::Qotd => (17, 0),
            Self::MessageSend => (18, 0),
            Self::Chargen => (19, 0),
            Self::Time => (37, 0),
            Self::HostNameServer => (42, 0),
            Self::Tacacs => (49, 0),
            Self::Dns => (53, 0),
            Self::BootpServer => (67, 0),
            Self::BootpClient => (68, 0),
            Self::Tftp => (69, 0),
            Self::Netrjs => (71, 3),
            Self::Http => (80, 0),
            Self::Kerberos => (88, 0),
            Self::DiCom => (104, 0),
            Self::CcsoNameServer => (105, 0),
            Self::RTelnet => (107, 0),
            Self::IBMSnaGateway => (108, 0),
            Self::OncRpc => (111, 0),
            Self::McIDAS => (112, 0),
            Self::UucpPathService => (117, 0),
            Self::SqlServices => (118, 0),
            Self::Ntp => (123, 0),
            Self::NxEdit => (126, 0),
            Self::DceEndpointResolution => (135, 0),
            Self::MicrosoftEpmap => (135, 0),
            Self::NetbiosNameService => (137, 0),
            Self::NetbiosDatagramService => (138, 0),
            Self::Bftp => (152, 0),
            Self::Sgmp => (153, 0),
            Self::Dmsp => (156, 0),
            Self::Snmp => (158, 0),
            Self::Snmptrap => (161, 0),
            Self::NetworkPostScript => (162, 0),
            Self::Vmnet => (170, 0),
            Self::Xdmcp => (175, 0),
            Self::Irc => (177, 0),
            Self::Smux => (194, 0),
            Self::AppletalkRouting => (199, 0),
            Self::AnsiZ3950 => (201, 0),
            Self::Ipx => (210, 0),
            Self::Mpp => (213, 0),
            Self::Imap3 => (218, 0),
            Self::Esro => (220, 0),
            Self::Arcisdms => (259, 0),
            Self::Bgmp => (262, 0),
            Self::HttpMgmt => (264, 0),
            Self::PkixTsp => (280, 0),
            Self::PtpEvent => (318, 0),
            Self::PtpGeneral => (319, 0),
            Self::MatipA => (320, 0),
            Self::MatipB => (350, 0),
            Self::CloantoNet1 => (351, 0),
            Self::Odmr => (356, 0),
            Self::Rpc2portmap => (366, 0),
            Self::Codaauth2 => (369, 0),
            Self::Securecast1 => (370, 0),
            Self::ClearCaseAlbd => (370, 0),
            Self::AmigaEnvoy => (371, 0),
            Self::HpDataAlarmManager => (376, 0),
            Self::Aurp => (383, 0),
            Self::DecnetPlus => (384, 0),
            Self::Ups => (387, 0),
            Self::Slp => (399, 0),
            Self::Nntp => (401, 0),
            Self::MobileIpAgent => (427, 0),
            Self::Https => (433, 0),
            Self::Snpp => (434, 0),
            Self::Quick_MicrosoftDs => (443, 0),
            Self::Kpasswd => (444, 0),
            Self::Tcpnethaspsrv => (445, 0),
            Self::Retrospect => (464, 0),
            Self::IsakmpIke => (475, 0),
            Self::Modbus => (497, 0),
            Self::CitadelFcp => (500, 0),
            Self::Comsat => (502, 0),
            Self::Who => (504, 0),
            Self::Syslog => (510, 0),
            Self::Rip => (512, 0),
            Self::Ripng => (513, 0),
            Self::Ncp => (514, 0),
            Self::Timed => (517, 0),
            Self::Rpc => (518, 0),
            Self::Netwall => (520, 0),
            Self::Commerce => (521, 0),
            Self::Dhcpv6Client => (524, 0),
            Self::Dhcpv6Server => (525, 0),
            Self::NewRwho => (530, 0),
            Self::Rtsp => (533, 0),
            Self::Rmonitor => (542, 0),
            Self::Monitor => (546, 0),
            Self::Nntps => (547, 0),
            Self::HttpRpcEpMap => (550, 0),
            Self::AsfRmcpIpmi => (554, 0),
            Self::Ipp => (560, 0),
            Self::Msdp => (561, 0),
            Self::SupportsoftNexusControl => (563, 0),
            Self::Sanity => (593, 0),
            Self::Ldp => (623, 0),
            Self::IeeeMms => (631, 0),
            Self::TincVpn => (635, 0),
            Self::IbmRmc => (639, 0),
            Self::Doom => (641, 0),
            Self::CorbaIiopSsl => (643, 0),
            Self::RealmRusd => (646, 0),
            Self::Vatp => (651, 0),
            Self::LinuxHaHeartbeat => (653, 0),
            Self::Olsr => (655, 0),
            Self::KerberosAdmin => (657, 0),
            Self::KerberosIv => (666, 0),
            Self::Rrh => (684, 0),
            Self::TellSend => (688, 0),
            Self::MdbsDaemon => (690, 0),
            Self::ModbusTcpSecurity => (694, 0),
            Self::NetconfSsh => (698, 0),
            Self::NetconfBeep => (749, 0),
            Self::NetconfSoapHttps => (750, 0),
            Self::NetconfSoapBeep => (753, 0),
            Self::Gdoi => (754, 0),
            Self::DnsOverQuic => (800, 0),
            Self::DnsOverDtls => (802, 0),
            Self::OwampControl => (830, 0),
            Self::TwampControl => (831, 0),
            Self::FtpsData => (832, 0),
            Self::FtpsControl => (833, 0),
            Self::Nas => (848, 0),
            Self::TelnetTls => (853, 0),
            Self::Pop3s => (861, 0),
            Self::WakeOnLan => (862, 0),
            Self::TorparkControl => (989, 0),

            Self::Pointcast => (990, 0),
            Self::CentroErp => (991, 0),
            Self::CupsAdmin => (992, 0),
            Self::KerberosMaster => (995, 0),
            Self::PasswdServer => (9, 0),
            Self::UserregServer => (82, 0),
            Self::Krbupdate => (90, 0),
            Self::Msx => (476, 14),
            Self::BrocadeSmiSRpc => (631, 0),
            Self::BrocadeSmiSRpcSsl => (751, 0),
            Self::VmwareEsxi => (752, 0),
            Self::PsWakeOnLan => (753, 0),
            Self::ZosNfs => (760, 0)
        }
    }

    pub fn to_string(&self) -> String {
        match self {
            Self::Echo => "Echo",
            Self::Discard => "Discard",
            Self::Systat => "Systat",
            Self::Daytime => "Daytime",
            Self::Qotd => "QOTD",
            Self::MessageSend => "Message Send",
            Self::Chargen => "Character Generator",
            Self::Time => "Time",
            Self::HostNameServer => "Host Name Server",
            Self::Tacacs => "TACACS",
            Self::Dns => "DNS",
            Self::BootpServer => "BOOTP Server",
            Self::BootpClient => "BOOTP Client",
            Self::Tftp => "TFTP",
            Self::Netrjs => "NETRJS",
            Self::Http => "HTTP",
            Self::Kerberos => "Kerberos",
            Self::DiCom => "DICOM",
            Self::CcsoNameServer => "CCSO Name Server",
            Self::RTelnet => "Remote Telnet",
            Self::IBMSnaGateway => "IBM SNA Gateway",
            Self::OncRpc => "ONC RPC",
            Self::McIDAS => "McIDAS",
            Self::UucpPathService => "UUCP Path Service",
            Self::SqlServices => "SQL Services",
            Self::Ntp => "NTP",
            Self::NxEdit => "NXEdit",
            Self::DceEndpointResolution => "DCE Endpoint Resolution",
            Self::MicrosoftEpmap => "Microsoft EPMAP",
            Self::NetbiosNameService => "NetBIOS Name Service",
            Self::NetbiosDatagramService => "NetBIOS Datagram Service",
            Self::Bftp => "BFTP",
            Self::Sgmp => "SGMP",
            Self::Dmsp => "DMSP",
            Self::Snmp => "SNMP",
            Self::Snmptrap => "SNMP Trap",
            Self::NetworkPostScript => "Network PostScript",
            Self::Vmnet => "VMNET",
            Self::Xdmcp => "XDMCP",
            Self::Irc => "IRC",
            Self::Smux => "SMUX",
            Self::AppletalkRouting => "AppleTalk Routing",
            Self::AnsiZ3950 => "ANSI Z39.50",
            Self::Ipx => "IPX",
            Self::Mpp => "MPP",
            Self::Imap3 => "IMAP3",
            Self::Esro => "ESRO",
            Self::Arcisdms => "ARCIS DMS",
            Self::Bgmp => "BGMP",
            Self::HttpMgmt => "HTTP Management",
            Self::PkixTsp => "PKIX Time Stamp Protocol",
            Self::PtpEvent => "PTP Event",
            Self::PtpGeneral => "PTP General",
            Self::MatipA => "MATIP A",
            Self::MatipB => "MATIP B",
            Self::CloantoNet1 => "Cloanto Net 1",
            Self::Odmr => "ODMR",
            Self::Rpc2portmap => "RPC2 Portmap",
            Self::Codaauth2 => "CODA Auth 2",
            Self::Securecast1 => "SecureCast 1",
            Self::ClearCaseAlbd => "ClearCase ALBD",
            Self::AmigaEnvoy => "Amiga Envoy",
            Self::HpDataAlarmManager => "HP Data Alarm Manager",
            Self::Aurp => "AURP",
            Self::DecnetPlus => "DECnet Plus",
            Self::Ups => "UPS",
            Self::Slp => "SLP",
            Self::Nntp => "NNTP",
            Self::MobileIpAgent => "Mobile IP Agent",
            Self::Https => "HTTPS",
            Self::Snpp => "SNPP",
            Self::Quick_MicrosoftDs => "Quick / Microsoft DS",
            Self::Kpasswd => "Kerberos Password",
            Self::Tcpnethaspsrv => "TCPNET HASP Server",
            Self::Retrospect => "Retrospect",
            Self::IsakmpIke => "ISAKMP/IKE",
            Self::Modbus => "Modbus",
            Self::CitadelFcp => "Citadel FCP",
            Self::Comsat => "Comsat",
            Self::Who => "Who",
            Self::Syslog => "Syslog",
            Self::Rip => "RIP",
            Self::Ripng => "RIPng",
            Self::Ncp => "NCP",
            Self::Timed => "Timed",
            Self::Rpc => "RPC",
            Self::Netwall => "Netwall",
            Self::Commerce => "Commerce",
            Self::Dhcpv6Client => "DHCPv6 Client",
            Self::Dhcpv6Server => "DHCPv6 Server",
            Self::NewRwho => "New RWHO",
            Self::Rtsp => "RTSP",
            Self::Rmonitor => "RMONITOR",
            Self::Monitor => "Monitor",
            Self::Nntps => "NNTPS",
            Self::HttpRpcEpMap => "HTTP RPC Endpoint Mapper",
            Self::AsfRmcpIpmi => "ASF RMCP/IPMI",
            Self::Ipp => "IPP",
            Self::Msdp => "MSDP",
            Self::SupportsoftNexusControl => "SupportSoft Nexus Control",
            Self::Sanity => "Sanity",
            Self::Ldp => "LDP",
            Self::IeeeMms => "IEEE MMS",
            Self::TincVpn => "Tinc VPN",
            Self::IbmRmc => "IBM RMC",
            Self::Doom => "Doom",
            Self::CorbaIiopSsl => "CORBA IIOP SSL",
            Self::RealmRusd => "REALM RUSD",
            Self::Vatp => "VATP",
            Self::LinuxHaHeartbeat => "Linux-HA Heartbeat",
            Self::Olsr => "OLSR",
            Self::KerberosAdmin => "Kerberos Admin",
            Self::KerberosIv => "Kerberos IV",
            Self::Rrh => "RRH",
            Self::TellSend => "TellSend",
            Self::MdbsDaemon => "MDBS Daemon",
            Self::ModbusTcpSecurity => "Modbus TCP Security",
            Self::NetconfSsh => "NETCONF over SSH",
            Self::NetconfBeep => "NETCONF over BEEP",
            Self::NetconfSoapHttps => "NETCONF over SOAP/HTTPS",
            Self::NetconfSoapBeep => "NETCONF over SOAP/BEEP",
            Self::Gdoi => "GDOI",
            Self::DnsOverQuic => "DNS over QUIC",
            Self::DnsOverDtls => "DNS over DTLS",
            Self::OwampControl => "OWAMP Control",
            Self::TwampControl => "TWAMP Control",
            Self::FtpsData => "FTPS Data",
            Self::FtpsControl => "FTPS Control",
            Self::Nas => "NAS",
            Self::TelnetTls => "Telnet over TLS",
            Self::Pop3s => "POP3S",
            Self::WakeOnLan => "Wake on LAN",
            Self::TorparkControl => "Torpark Control",

            Self::Pointcast => "[UO] PointCast",
            Self::CentroErp => "[UO] Centro ERP",
            Self::CupsAdmin => "[UO] CUPS Admin",
            Self::KerberosMaster => "[UO] Kerberos Master",
            Self::PasswdServer => "[UO] Password Server",
            Self::UserregServer => "[UO] User Registration Server",
            Self::Krbupdate => "[UO] Kerberos Update",
            Self::Msx => "[UO] MSX",
            Self::BrocadeSmiSRpc => "[UO] Brocade SMI-S RPC",
            Self::BrocadeSmiSRpcSsl => "[UO] Brocade SMI-S RPC SSL",
            Self::VmwareEsxi => "[UO] VMware ESXi",
            Self::PsWakeOnLan => "[UO] PS Wake on LAN",
            Self::ZosNfs => "[UO] z/OS NFS"
        }.to_string()
    }
}
