#[derive(Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub enum TcpPorts {
    Echo,
    Discard,
    Systat,
    Daytime,
    Qotd,
    MessageSend,
    Chargen,
    Time,
    Tacacs,
    Dns,
    Netrjs,
    Http,
    Kerberos,
    Dicom,
    Ccso,
    Rtelnet,
    Sna,
    OncRpc,
    Mcidas,
    UucpPath,
    SqlService,
    NxEdit,
    DceEndpoint,
    EpmMap,
    NetbiosName,
    Bftp,
    Sgmp,
    Sql,
    Dmsp,
    SnmpTrap,
    NetPostScript,
    Vmnet,
    Xdmcp,
    Irc,
    Smux,
    AppletalkRouting,
    AnsiZ3950,
    Ipx,
    Mpp,
    Imap3,
    Esro,
    Arcisdms,
    Bgmp,
    HttpMgmt,
    PkixTsp,
    MatipA,
    MatipB,
    CloantoNet1,
    Odmr,
    Rpc2portmap,
    Codaauth2,
    ClearcaseAlbd,
    AmigaEnvoy,
    HpDataAlarm,
    RemoteNetServer,
    Aurp,
    Decnet,
    Ups,
    Slp,
    Nntp,
    MobileIp,
    Https,
    Snpp,
    MicrosoftDs,
    Kpasswd,
    Tcpnethaspsrv,
    Retrospect,
    Modbus,
    Citadel,
    Firstclass,
    Ncp,
    Rpc,
    Commerce,
    Dhcpv6Client,
    Dhcpv6Server,
    NewRwho,
    Rtsp,
    Nntps,
    HttpRpcEpMap,
    Ipp,
    RlzDbase,
    Msdp,
    SupportsoftCtrl,
    Sanity,
    Ldp,
    IeeeMms,
    SupportsoftData,
    TincVpn,
    IbmRmc,
    Doom,
    CorbaIiopSsl,
    RealmRusd,
    Vatp,
    LinuxHa,
    KerberosAdm,
    Rrh,
    TellSend,
    MdbsDaemon,
    ModbusTcpSec,
    NetconfSsh,
    NetconfBeep,
    NetconfSoapHttps,
    NetconfSoapBeep,
    Gdoi,
    OwampCtrl,
    TwampCtrl,
    FtpsData,
    FtpsCtrl,
    Nas,
    Telnets,
    Pop3s,
    Ident,
    UrlRendezvous,
    Tcpmux,
    FtpData,
    FtpCtrl,
    Ssh,
    Telnet,
    Smtp,
    Whois,
    Gopher,
    Finger,
    Supdup,
    NicHostname,
    IsoTsap,
    Pop2,
    Pop3,
    Auth,
    Sftp,
    NntpRetrieval,
    NetbiosSession,
    Imap,
    Bgp,
    Qmtp,
    MacServerAdmin,
    UnidataLdm,
    Ldap,
    MicrosoftDsSmb,
    Lpd,
    Netnews,
    Afp,
    MsgSubmit,
    Ldaps,
    MacAdmin,
    IeeeMmsSsl,
    Cmp,
    Imaps,
    Novastor,
    Rpki,
    Rexec,
    Rlogin,
    Efs,
    Uucp,
    Klogin,
    Kshell,
    Remotefs,
    Filemaker,
    Syslog,
    TunnelProfile,
    DhcpFailover,
    Rrp,
    Mms,
    Acap,
    MsExchange,
    Epp,
    Lmp,
    Iris,
    Silc,
    CiscoTdp,
    Tbrpf,
    DhcpFailover2,
    DnsTls,
    Iscsi,
    Rsync,
    BindRndc,
    Pointcast,
    CentroErp,
    CupsAdmin,
    KerberosMaster,
    KrbUpdate,
    Msx,
    BrocadeSmisRpc,
    BrocadeSmisSsl,
    VmwareEsxi,
    ZosNfs,
    Netstat,
    MacosPwdServer,
    XsanAdmin,
    OdProxy,
    PanoramaHaSync,
    Torpark,
    ThinlincWeb,
    GoGlobal,
    Rsh,
    Plan9,
    AirservNg,
    Krb5Prop,
    Conserver,
    Spamd,
    NetTcpShare,
    Flash,
    Cddbp,
    IbmRemoteCtrl,
    EsxiMgmt,
    Vpn1Https,
    RemoteWebWorkplace,
    Lustre,
    ThinlincAdmin
}

impl TcpPorts {

    pub fn from_code(code: u16) -> Result<Self, String> {
        for c in [
            Self::Echo,
            Self::Discard,
            Self::Systat,
            Self::Daytime,
            Self::Qotd,
            Self::MessageSend,
            Self::Chargen,
            Self::Time,
            Self::Tacacs,
            Self::Dns,
            Self::Netrjs,
            Self::Http,
            Self::Kerberos,
            Self::Dicom,
            Self::Ccso,
            Self::Rtelnet,
            Self::Sna,
            Self::OncRpc,
            Self::Mcidas,
            Self::UucpPath,
            Self::SqlService,
            Self::NxEdit,
            Self::DceEndpoint,
            Self::EpmMap,
            Self::NetbiosName,
            Self::Bftp,
            Self::Sgmp,
            Self::Sql,
            Self::Dmsp,
            Self::SnmpTrap,
            Self::NetPostScript,
            Self::Vmnet,
            Self::Xdmcp,
            Self::Irc,
            Self::Smux,
            Self::AppletalkRouting,
            Self::AnsiZ3950,
            Self::Ipx,
            Self::Mpp,
            Self::Imap3,
            Self::Esro,
            Self::Arcisdms,
            Self::Bgmp,
            Self::HttpMgmt,
            Self::PkixTsp,
            Self::MatipA,
            Self::MatipB,
            Self::CloantoNet1,
            Self::Odmr,
            Self::Rpc2portmap,
            Self::Codaauth2,
            Self::ClearcaseAlbd,
            Self::AmigaEnvoy,
            Self::HpDataAlarm,
            Self::RemoteNetServer,
            Self::Aurp,
            Self::Decnet,
            Self::Ups,
            Self::Slp,
            Self::Nntp,
            Self::MobileIp,
            Self::Https,
            Self::Snpp,
            Self::MicrosoftDs,
            Self::Kpasswd,
            Self::Tcpnethaspsrv,
            Self::Retrospect,
            Self::Modbus,
            Self::Citadel,
            Self::Firstclass,
            Self::Ncp,
            Self::Rpc,
            Self::Commerce,
            Self::Dhcpv6Client,
            Self::Dhcpv6Server,
            Self::NewRwho,
            Self::Rtsp,
            Self::Nntps,
            Self::HttpRpcEpMap,
            Self::Ipp,
            Self::RlzDbase,
            Self::Msdp,
            Self::SupportsoftCtrl,
            Self::Sanity,
            Self::Ldp,
            Self::IeeeMms,
            Self::SupportsoftData,
            Self::TincVpn,
            Self::IbmRmc,
            Self::Doom,
            Self::CorbaIiopSsl,
            Self::RealmRusd,
            Self::Vatp,
            Self::LinuxHa,
            Self::KerberosAdm,
            Self::Rrh,
            Self::TellSend,
            Self::MdbsDaemon,
            Self::ModbusTcpSec,
            Self::NetconfSsh,
            Self::NetconfBeep,
            Self::NetconfSoapHttps,
            Self::NetconfSoapBeep,
            Self::Gdoi,
            Self::OwampCtrl,
            Self::TwampCtrl,
            Self::FtpsData,
            Self::FtpsCtrl,
            Self::Nas,
            Self::Telnets,
            Self::Pop3s,
            Self::Ident,
            Self::UrlRendezvous,
            Self::Tcpmux,
            Self::FtpData,
            Self::FtpCtrl,
            Self::Ssh,
            Self::Telnet,
            Self::Smtp,
            Self::Whois,
            Self::Gopher,
            Self::Finger,
            Self::Supdup,
            Self::NicHostname,
            Self::IsoTsap,
            Self::Pop2,
            Self::Pop3,
            Self::Auth,
            Self::Sftp,
            Self::NntpRetrieval,
            Self::NetbiosSession,
            Self::Imap,
            Self::Bgp,
            Self::Qmtp,
            Self::MacServerAdmin,
            Self::UnidataLdm,
            Self::Ldap,
            Self::MicrosoftDsSmb,
            Self::Lpd,
            Self::Netnews,
            Self::Afp,
            Self::MsgSubmit,
            Self::Ldaps,
            Self::MacAdmin,
            Self::IeeeMmsSsl,
            Self::Cmp,
            Self::Imaps,
            Self::Novastor,
            Self::Rpki,
            Self::Rexec,
            Self::Rlogin,
            Self::Efs,
            Self::Uucp,
            Self::Klogin,
            Self::Kshell,
            Self::Remotefs,
            Self::Filemaker,
            Self::Syslog,
            Self::TunnelProfile,
            Self::DhcpFailover,
            Self::Rrp,
            Self::Mms,
            Self::Acap,
            Self::MsExchange,
            Self::Epp,
            Self::Lmp,
            Self::Iris,
            Self::Silc,
            Self::CiscoTdp,
            Self::Tbrpf,
            Self::DhcpFailover2,
            Self::DnsTls,
            Self::Iscsi,
            Self::Rsync,
            Self::BindRndc,
            Self::Pointcast,
            Self::CentroErp,
            Self::CupsAdmin,
            Self::KerberosMaster,
            Self::KrbUpdate,
            Self::Msx,
            Self::BrocadeSmisRpc,
            Self::BrocadeSmisSsl,
            Self::VmwareEsxi,
            Self::ZosNfs,
            Self::Netstat,
            Self::MacosPwdServer,
            Self::XsanAdmin,
            Self::OdProxy,
            Self::PanoramaHaSync,
            Self::Torpark,
            Self::ThinlincWeb,
            Self::GoGlobal,
            Self::Rsh,
            Self::Plan9,
            Self::AirservNg,
            Self::Krb5Prop,
            Self::Conserver,
            Self::Spamd,
            Self::NetTcpShare,
            Self::Flash,
            Self::Cddbp,
            Self::IbmRemoteCtrl,
            Self::EsxiMgmt,
            Self::Vpn1Https,
            Self::RemoteWebWorkplace,
            Self::Lustre,
            Self::ThinlincAdmin
        ] {
            let (x, w) = c.get_code();
            if x >= code && x + w <= code {
                return Ok(c);
            }
        }

        Err(format!("Couldn't find for code: {}", code))
    }

    pub fn get_code(&self) -> (u16, u16) {
        match self {
            Self::Echo => (7, 0),
            Self::Discard => (9, 0),
            Self::Systat => (11, 0),
            Self::Daytime => (13, 0),
            Self::Qotd => (17, 0),
            Self::MessageSend => (18, 0),
            Self::Chargen => (19, 0),
            Self::Time => (37, 0),
            Self::Tacacs => (49, 0),
            Self::Dns => (53, 0),
            Self::Netrjs => (71, 3),
            Self::Http => (80, 0),
            Self::Kerberos => (88, 0),
            Self::Dicom => (104, 0),
            Self::Ccso => (105, 0),
            Self::Rtelnet => (107, 0),
            Self::Sna => (108, 0),
            Self::OncRpc => (111, 0),
            Self::Mcidas => (112, 0),
            Self::UucpPath => (117, 0),
            Self::SqlService => (118, 0),
            Self::NxEdit => (126, 0),
            Self::DceEndpoint => (135, 0),
            Self::EpmMap => (135, 0),
            Self::NetbiosName => (137, 0),
            Self::Bftp => (152, 0),
            Self::Sgmp => (153, 0),
            Self::Sql => (156, 0),
            Self::Dmsp => (158, 0),
            Self::SnmpTrap => (162, 0),
            Self::NetPostScript => (170, 0),
            Self::Vmnet => (175, 0),
            Self::Xdmcp => (177, 0),
            Self::Irc => (194, 0),
            Self::Smux => (199, 0),
            Self::AppletalkRouting => (201, 0),
            Self::AnsiZ3950 => (210, 0),
            Self::Ipx => (213, 0),
            Self::Mpp => (218, 0),
            Self::Imap3 => (220, 0),
            Self::Esro => (259, 0),
            Self::Arcisdms => (262, 0),
            Self::Bgmp => (264, 0),
            Self::HttpMgmt => (280, 0),
            Self::PkixTsp => (318, 0),
            Self::MatipA => (350, 0),
            Self::MatipB => (351, 0),
            Self::CloantoNet1 => (356, 0),
            Self::Odmr => (366, 0),
            Self::Rpc2portmap => (369, 0),
            Self::Codaauth2 => (370, 0),
            Self::ClearcaseAlbd => (371, 0),
            Self::AmigaEnvoy => (376, 0),
            Self::HpDataAlarm => (383, 0),
            Self::RemoteNetServer => (384, 0),
            Self::Aurp => (387, 0),
            Self::Decnet => (399, 0),
            Self::Ups => (401, 0),
            Self::Slp => (427, 0),
            Self::Nntp => (433, 0),
            Self::MobileIp => (434, 0),
            Self::Https => (443, 0),
            Self::Snpp => (444, 0),
            Self::MicrosoftDs => (445, 0),
            Self::Kpasswd => (464, 0),
            Self::Tcpnethaspsrv => (475, 0),
            Self::Retrospect => (497, 0),
            Self::Modbus => (502, 0),
            Self::Citadel => (504, 0),
            Self::Firstclass => (510, 0),
            Self::Ncp => (524, 0),
            Self::Rpc => (530, 0),
            Self::Commerce => (542, 0),
            Self::Dhcpv6Client => (546, 0),
            Self::Dhcpv6Server => (547, 0),
            Self::NewRwho => (550, 0),
            Self::Rtsp => (554, 0),
            Self::Nntps => (563, 0),
            Self::HttpRpcEpMap => (593, 0),
            Self::Ipp => (631, 0),
            Self::RlzDbase => (635, 0),
            Self::Msdp => (639, 0),
            Self::SupportsoftCtrl => (641, 0),
            Self::Sanity => (643, 0),
            Self::Ldp => (646, 0),
            Self::IeeeMms => (651, 0),
            Self::SupportsoftData => (653, 0),
            Self::TincVpn => (655, 0),
            Self::IbmRmc => (657, 0),
            Self::Doom => (666, 0),
            Self::CorbaIiopSsl => (684, 0),
            Self::RealmRusd => (688, 0),
            Self::Vatp => (690, 0),
            Self::LinuxHa => (694, 0),
            Self::KerberosAdm => (749, 0),
            Self::Rrh => (753, 0),
            Self::TellSend => (754, 0),
            Self::MdbsDaemon => (800, 0),
            Self::ModbusTcpSec => (802, 0),
            Self::NetconfSsh => (830, 0),
            Self::NetconfBeep => (831, 0),
            Self::NetconfSoapHttps => (832, 0),
            Self::NetconfSoapBeep => (833, 0),
            Self::Gdoi => (848, 0),
            Self::OwampCtrl => (861, 0),
            Self::TwampCtrl => (862, 0),
            Self::FtpsData => (989, 0),
            Self::FtpsCtrl => (990, 0),
            Self::Nas => (991, 0),
            Self::Telnets => (992, 0),
            Self::Pop3s => (995, 0),
            Self::Ident => (113, 0),
            Self::UrlRendezvous => (465, 0),
            Self::Tcpmux => (1, 0),
            Self::FtpData => (20, 0),
            Self::FtpCtrl => (21, 0),
            Self::Ssh => (22, 0),
            Self::Telnet => (23, 0),
            Self::Smtp => (25, 0),
            Self::Whois => (43, 0),
            Self::Gopher => (70, 0),
            Self::Finger => (79, 0),
            Self::Supdup => (95, 0),
            Self::NicHostname => (101, 0),
            Self::IsoTsap => (102, 0),
            Self::Pop2 => (109, 0),
            Self::Pop3 => (110, 0),
            Self::Auth => (113, 0),
            Self::Sftp => (115, 0),
            Self::NntpRetrieval => (119, 0),
            Self::NetbiosSession => (139, 0),
            Self::Imap => (143, 0),
            Self::Bgp => (179, 0),
            Self::Qmtp => (209, 0),
            Self::MacServerAdmin => (311, 0),
            Self::UnidataLdm => (388, 0),
            Self::Ldap => (389, 0),
            Self::MicrosoftDsSmb => (445, 0),
            Self::Lpd => (515, 0),
            Self::Netnews => (532, 0),
            Self::Afp => (548, 0),
            Self::MsgSubmit => (587, 0),
            Self::Ldaps => (636, 0),
            Self::MacAdmin => (660, 0),
            Self::IeeeMmsSsl => (695, 0),
            Self::Cmp => (829, 0),
            Self::Imaps => (993, 0),
            Self::Novastor => (308, 0),
            Self::Rpki => (323, 0),
            Self::Rexec => (512, 0),
            Self::Rlogin => (513, 0),
            Self::Efs => (520, 0),
            Self::Uucp => (540, 0),
            Self::Klogin => (543, 0),
            Self::Kshell => (544, 0),
            Self::Remotefs => (556, 0),
            Self::Filemaker => (591, 0),
            Self::Syslog => (601, 0),
            Self::TunnelProfile => (604, 0),
            Self::DhcpFailover => (647, 0),
            Self::Rrp => (648, 0),
            Self::Mms => (654, 0),
            Self::Acap => (674, 0),
            Self::MsExchange => (691, 0),
            Self::Epp => (700, 0),
            Self::Lmp => (701, 0),
            Self::Iris => (702, 0),
            Self::Silc => (706, 0),
            Self::CiscoTdp => (711, 0),
            Self::Tbrpf => (712, 0),
            Self::DhcpFailover2 => (847, 0),
            Self::DnsTls => (853, 0),
            Self::Iscsi => (860, 0),
            Self::Rsync => (873, 0),
            Self::BindRndc => (953, 0),
            Self::Pointcast => (90, 0),
            Self::CentroErp => (476, 14),
            Self::CupsAdmin => (631, 0),
            Self::KerberosMaster => (751, 0),
            Self::KrbUpdate => (760, 0),
            Self::Msx => (777, 0),
            Self::BrocadeSmisRpc => (897, 0),
            Self::BrocadeSmisSsl => (898, 0),
            Self::VmwareEsxi => (902, 0),
            Self::ZosNfs => (1023, 0),
            Self::Netstat => (15, 0),
            Self::MacosPwdServer => (106, 0),
            Self::XsanAdmin => (312, 0),
            Self::OdProxy => (625, 0),
            Self::PanoramaHaSync => (28, 0),
            Self::Torpark => (81, 0),
            Self::ThinlincWeb => (300, 0),
            Self::GoGlobal => (491, 0),
            Self::Rsh => (514, 0),
            Self::Plan9 => (564, 0),
            Self::AirservNg => (666, 0),
            Self::Krb5Prop => (754, 0),
            Self::Conserver => (782, 0),
            Self::Spamd => (783, 0),
            Self::NetTcpShare => (808, 0),
            Self::Flash => (843, 0),
            Self::Cddbp => (888, 0),
            Self::IbmRemoteCtrl => (888, 0),
            Self::EsxiMgmt => (903, 0),
            Self::Vpn1Https => (981, 0),
            Self::RemoteWebWorkplace => (987, 0),
            Self::Lustre => (988, 0),
            Self::ThinlincAdmin => (1010, 0),
        }
    }

    pub fn to_string(&self) -> String {
        match self {
            Self::Echo => "Echo",
            Self::Discard => "Discard",
            Self::Systat => "Systat",
            Self::Daytime => "Daytime",
            Self::Qotd => "QOTD",
            Self::MessageSend => "Message Send",
            Self::Chargen => "Character Generator",
            Self::Time => "Time",
            Self::Tacacs => "TACACS",
            Self::Dns => "DNS",
            Self::Netrjs => "NETRJS",
            Self::Http => "HTTP",
            Self::Kerberos => "Kerberos",
            Self::Dicom => "DICOM",
            Self::Ccso => "CCSO",
            Self::Rtelnet => "RTelnet",
            Self::Sna => "SNA",
            Self::OncRpc => "ONC RPC",
            Self::Mcidas => "McIDAS",
            Self::UucpPath => "UUCP Path Service",
            Self::SqlService => "SQL Service",
            Self::NxEdit => "NXEdit",
            Self::DceEndpoint => "DCE Endpoint Mapper",
            Self::EpmMap => "EPMAP",
            Self::NetbiosName => "NetBIOS Name Service",
            Self::Bftp => "BFTP",
            Self::Sgmp => "SGMP",
            Self::Sql => "SQL Database",
            Self::Dmsp => "DMSP",
            Self::SnmpTrap => "SNMP Trap",
            Self::NetPostScript => "NetPostScript Service",
            Self::Vmnet => "VMNet",
            Self::Xdmcp => "XDMCP",
            Self::Irc => "IRC",
            Self::Smux => "SMUX",
            Self::AppletalkRouting => "AppleTalk Routing",
            Self::AnsiZ3950 => "ANSI Z39.50",
            Self::Ipx => "IPX",
            Self::Mpp => "MPP",
            Self::Imap3 => "IMAP Version 3",
            Self::Esro => "ESRO",
            Self::Arcisdms => "ARCISDMS",
            Self::Bgmp => "BGMP",
            Self::HttpMgmt => "HTTP Management",
            Self::PkixTsp => "PKIX Time Stamp Protocol",
            Self::MatipA => "MATIP-A",
            Self::MatipB => "MATIP-B",
            Self::CloantoNet1 => "Cloanto Net 1",
            Self::Odmr => "ODMR (On-Demand Mail Relay)",
            Self::Rpc2portmap => "RPC2 Portmap",
            Self::Codaauth2 => "CodaAuth",
            Self::ClearcaseAlbd => "ClearCase ALBD",
            Self::AmigaEnvoy => "Amiga Envoy",
            Self::HpDataAlarm => "HP Data Alarm Manager",
            Self::RemoteNetServer => "Remote Network Server",
            Self::Aurp => "AURP",
            Self::Decnet => "DECnet",
            Self::Ups => "UPS",
            Self::Slp => "SLP",
            Self::Nntp => "NNTP",
            Self::MobileIp => "Mobile I",
            Self::Https => "HTTPS",
            Self::Snpp => "SNPP",
            Self::MicrosoftDs => "MSDS",
            Self::Kpasswd => "Kpasswd",
            Self::Tcpnethaspsrv => "TCP NetHASP Service",
            Self::Retrospect => "Retrospect Backup",
            Self::Modbus => "Modbus",
            Self::Citadel => "Citadel",
            Self::Firstclass => "FirstClass Communication",
            Self::Ncp => "NCP",
            Self::Rpc => "RPC",
            Self::Commerce => "Commerce",
            Self::Dhcpv6Client => "DHCPv6 Client",
            Self::Dhcpv6Server => "DHCPv6 Server",
            Self::NewRwho => "New Remote Who",
            Self::Rtsp => "RTSP",
            Self::Nntps => "NNTPS",
            Self::HttpRpcEpMap => "HTTP RPC Endpoint Mapper",
            Self::Ipp => "IPP",
            Self::RlzDbase => "RLZ Database",
            Self::Msdp => "MSDP",
            Self::SupportsoftCtrl => "SupportSoft Control",
            Self::Sanity => "Sanity",
            Self::Ldp => "LDP",
            Self::IeeeMms => "IEEE MMS",
            Self::SupportsoftData => "SupportSoft Data",
            Self::TincVpn => "TINC VPN",
            Self::IbmRmc => "RMC",
            Self::Doom => "Doom Game",
            Self::CorbaIiopSsl => "CORBA IIOP over SSL",
            Self::RealmRusd => "Realm RUSD",
            Self::Vatp => "VATP",
            Self::LinuxHa => "Linux-HA",
            Self::KerberosAdm => "Kerberos Admin",
            Self::Rrh => "RRH",
            Self::TellSend => "TellSend",
            Self::MdbsDaemon => "MDBS Daemon",
            Self::ModbusTcpSec => "Modbus TCP Security",
            Self::NetconfSsh => "NETCONF over SSH",
            Self::NetconfBeep => "NETCONF over BEEP",
            Self::NetconfSoapHttps => "NETCONF SOAP over HTTPS",
            Self::NetconfSoapBeep => "NETCONF SOAP over BEEP",
            Self::Gdoi => "GDOI",
            Self::OwampCtrl => "OWAMP Control",
            Self::TwampCtrl => "TWAMP Control",
            Self::FtpsData => "FTPS Data",
            Self::FtpsCtrl => "FTPS Control",
            Self::Nas => "NAS",
            Self::Telnets => "Telnets",
            Self::Pop3s => "POP3S",
            Self::Ident => "Ident",
            Self::UrlRendezvous => "URL Rendezvous",
            Self::Tcpmux => "TCPMUX",
            Self::FtpData => "FTP Data",
            Self::FtpCtrl => "FTP Control",
            Self::Ssh => "SSH",
            Self::Telnet => "Telnet",
            Self::Smtp => "SMTP",
            Self::Whois => "Whois",
            Self::Gopher => "Gopher",
            Self::Finger => "Finger",
            Self::Supdup => "SUPDUP",
            Self::NicHostname => "NIC Hostname",
            Self::IsoTsap => "ISO TSAP",
            Self::Pop2 => "POP2",
            Self::Pop3 => "POP3",
            Self::Auth => "AUTH",
            Self::Sftp => "SFTP",
            Self::NntpRetrieval => "NNTP Retrieval",
            Self::NetbiosSession => "NetBIOS Session Service",
            Self::Imap => "IMAP",
            Self::Bgp => "BGP",
            Self::Qmtp => "QMTP",
            Self::MacServerAdmin => "Mac Server Admin",
            Self::UnidataLdm => "Unidata LDM",
            Self::Ldap => "LDAP",
            Self::MicrosoftDsSmb => "Microsoft DS SMB",
            Self::Lpd => "LPD",
            Self::Netnews => "Netnews",
            Self::Afp => "AFP",
            Self::MsgSubmit => "Message Submission",
            Self::Ldaps => "LDAPS",
            Self::MacAdmin => "Mac Admin",
            Self::IeeeMmsSsl => "IEEE MMS over SSL",
            Self::Cmp => "CMP",
            Self::Imaps => "IMAPS (IMAP over SSL)",
            Self::Novastor => "NovaStor Backup",
            Self::Rpki => "RPKI (Resource Public Key Infrastructure)",
            Self::Rexec => "REXEC",
            Self::Rlogin => "RLOGIN",
            Self::Efs => "EFS",
            Self::Uucp => "UUCP",
            Self::Klogin => "KLOGIN",
            Self::Kshell => "KShell",
            Self::Remotefs => "Remote File System",
            Self::Filemaker => "FileMaker",
            Self::Syslog => "Syslog",
            Self::TunnelProfile => "Tunnel Profile",
            Self::DhcpFailover => "DHCP Failover",
            Self::Rrp => "RRP",
            Self::Mms => "MMS",
            Self::Acap => "ACAP",
            Self::MsExchange => "Microsoft Exchange",
            Self::Epp => "EPP",
            Self::Lmp => "LMP",
            Self::Iris => "IRIS (Internet Registry Information Service)",
            Self::Silc => "SILC (Secure Internet Live Conferencing)",
            Self::CiscoTdp => "Cisco TDP",
            Self::Tbrpf => "TBRPF (Topology Broadcast Based on Reverse-Path Forwarding)",
            Self::DhcpFailover2 => "DHCP Failover",
            Self::DnsTls => "DNS over TLS",
            Self::Iscsi => "iSCSI",
            Self::Rsync => "Rsync",
            Self::BindRndc => "BIND RNDC",
            Self::Pointcast => "Pointcast",
            Self::CentroErp => "Centro ERP",
            Self::CupsAdmin => "CUPS Admin",
            Self::KerberosMaster => "Kerberos Master",
            Self::KrbUpdate => "KRB Update",
            Self::Msx => "MSX",
            Self::BrocadeSmisRpc => "Brocade SMIS RPC",
            Self::BrocadeSmisSsl => "Brocade SMIS over SSL",
            Self::VmwareEsxi => "VMware ESXi",
            Self::ZosNfs => "ZOS NFS",
            Self::Netstat => "Netstat",
            Self::MacosPwdServer => "macOS Password Server",
            Self::XsanAdmin => "Xsan Admin",
            Self::OdProxy => "OD Proxy",
            Self::PanoramaHaSync => "Panorama HA Sync",
            Self::Torpark => "Torpark",
            Self::ThinlincWeb => "ThinLinc Web",
            Self::GoGlobal => "GoGlobal",
            Self::Rsh => "RSH",
            Self::Plan9 => "Plan 9",
            Self::AirservNg => "Airserv NG",
            Self::Krb5Prop => "Krb5Prop",
            Self::Conserver => "Conserver",
            Self::Spamd => "SPAMD",
            Self::NetTcpShare => "NetTCP Share",
            Self::Flash => "Flash",
            Self::Cddbp => "CDDBP",
            Self::IbmRemoteCtrl => "IBM Remote Control",
            Self::EsxiMgmt => "ESXi Management",
            Self::Vpn1Https => "VPN-1 HTTPS",
            Self::RemoteWebWorkplace => "Remote Web Workplace",
            Self::Lustre => "Lustre File System",
            Self::ThinlincAdmin => "ThinLinc Admin",
        }.to_string()
    }
}
